### ISSUE TITLE
Capacity issue - I can't manage to get capacity since last week

### ISSUE THREAD

**Issue by azaceta** [openshift-labs/learn-katacoda#1183]
I've been trying several (many) times a day since aprox last Thursday-Friday for several scenarios and every time the system is out of capacity.
Is it running into any issue?
Looking at the open issues it looks it's not only me, is it?

**Comment by ryanj** [comment]
Were these errors with the subsystems content, or istio?  We have had a few reports about those recently

**Comment by azaceta** [comment]
They are in the basic introduction to containers modules, like: [https://learn.openshift.com/subsystems/container-internals-lab-2-0-part-1](https://learn.openshift.com/subsystems/container-internals-lab-2-0-part-1)
And [https://learn.openshift.com/subsystems/container-internals-lab-2-0-part-2](https://learn.openshift.com/subsystems/container-internals-lab-2-0-part-2)
The message always being the same `We are currently at capacity with no additional nodes available. Please check back in 10 minutes.`
But others outside that module, like the [Getting started with Helm 3](https://learn.openshift.com/developing-on-openshift/helm/), provision themselves properly.

**Comment by azaceta** [comment]
Team, this is still happening, I haven't been able to open those labs at all, always capacity issues while other labs work properly. Any option to get those fixed?
Part 3 is the same ([https://learn.openshift.com/subsystems/container-internals-lab-2-0-part-3](https://learn.openshift.com/subsystems/container-internals-lab-2-0-part-3)) and I guess the rest will be also the same, it seems there's an issue with this container internals labs.

**Comment by jdob** [comment]
We had a problem with the image that backed that series of scenarios. We've implemented a change and I was just able to access the scenario. 

I'm going to close this out since the specific issue first identified by this bug has been addressed. That's not to say we won't potentially bump into capacity issues in the future, so please feel free to open a new request if you encounter that error again (it will be a different issue since the old image has been retired entirely).

Thanks :)
