### ISSUE TITLE
Unable to login from the dashboard 

### ISSUE THREAD

**Issue by idovapner** [openshift-labs/learn-katacoda#123]
Hi, 

I tried to log in several times from the dashboard and I got the following messages: 
"Error
Invalid request
The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.
Return to the console."

User name: developer 
Password: developer

from the Terminal I can access, but from the dashboard, I cant. 

Best Regards,
Ido

**Comment by mhausenblas** [comment]
Which scenario are you talking about @idovapner?

**Comment by BenHall** [comment]
Thanks for letting us know, this is likely a cookie/proxy issue to Katacoda. 

Could you try and login with the Openshift 3.7 environment please? https://learn.openshift.com/playgrounds/openshift37/

**Comment by idovapner** [comment]
[cid:image001.png@01D392BA.DB864AE0]
The same issue.

**Comment by GrahamDumpleton** [comment]
This can happen if you are restarting scenarios quite frequently, so something to do with caching of cookies and potential re-use of environment hostname you are given for a specific scenario.

If you select on the "+" in menu bar and select option for 'View HTTP port 8443 on hist 1' to bring up web console in separate tab/window instead of a frame it has always then worked for me. So perhaps something specific related to frames.

![image](https://user-images.githubusercontent.com/507637/35194439-81fa192a-feee-11e7-8baa-9e09cbe04e39.png)

**Comment by idovapner** [comment]
Hey there,

We have the same issue with several computers – from some laptops we can login and from others, we can't.
Unfortunate, this action plan doesn’t work.

We removed the cache, Installed new web browser with different versions, but still we get the same issue.

Best Regards,
Ido

**Comment by idovapner** [comment]
Know we have several laptops that with the same issue:
[cid:image001.png@01D39441.EDAC3F30]
We can't connect to the environment anymore.

Best Regards,
Ido

**Comment by GrahamDumpleton** [comment]
Are they all connecting via a corporate firewall/proxy that does caching? If you are all connecting out via the same proxy and it is doing strange things, it could be interfering.

**Comment by idovapner** [comment]
we also tried from another ADSL connection line - the same issue (without any FW/Proxy)

________________________________

**Comment by mhausenblas** [comment]
Seems stale, please re-open if it persists.
