### ISSUE TITLE
parksmap-katacoda image does not display map after route created

### ISSUE THREAD

**Issue by masterclyde** [openshift-labs/learn-katacoda#439]
Site responds, however only with Map Visualizer on OpenShift 3 in the upper left hand corner.  Grey scale and streen buttons appear and the +/- buttons also appear, but no map is displayed.

**Comment by mr-beerkiss** [comment]
The same issue for me, I checked the console logs and the tiles fail to load due to HTTP 401.  

Example url: https://api.tiles.mapbox.com/v4/mapbox.light/4/6/8.png?access_token=pk.eyJ1Ijoiam9yZ2Vtb3JhbGVzcG91IiwiYSI6ImNpemR4ODE2ajAwNDcycW8xY2tybTFqejEifQ.zPgwmgYDgWemYRMXHYynLQ

**Comment by chandan-io** [comment]
I am having the same issue as described by masterclyde.

![image](https://user-images.githubusercontent.com/9473485/60287109-37e4d100-9965-11e9-82af-d635cc8241e5.png)

**Comment by danielhelfand** [comment]
Apologies for not addressing this sooner, but this issue is being addressed in #499. This is occurring because the sample parksmap application used in the image `openshiftroadshow/parksmap-katacoda:1.0.0` relied on a key for an external API. #499 will migrate the sample application a new API that does not require a key. 

You can view the new tutorial here, which is also being updated to OpenShift 3.11 [here](https://www.katacoda.com/dhelfand/courses/introduction/getting-started). It will require the creation of a katacoda account though.
