### ISSUE TITLE
Issue in "Developing with odo"

### ISSUE THREAD

**Issue by alexkieling** [openshift-labs/learn-katacoda#461]
The following error happened during step 4:
```
$ odo create java backend --binary target/wildwest-1.0.jar
 ✓   Checking component
 ✓   Checking component version
 ✗   Creating component backend
image stream java with tag latest not found in openshift and myproject namespaces
```

**Comment by danielhelfand** [comment]
@alexkieling This is probably due to Java not being available in the OpenShift catalog during the tutorial. There are occasionally issues loading the scenario with all the proper settings in the environment. A workaround for this is to run the following from the command line in the scenario:

```
curl -kL https://gist.github.com/jorgemoralespou/033c27a354406d7c5111711346e79b01/raw 2> /dev/null | oc apply -n openshift --as system:admin -f -
```

This will add Java a catalog component option and should fix the command the scenario if you run into this. Another alternative is to try reloading the scenario. 

In general, though, there does need to be some effort put into ways of assuring the configuration loads properly in the environment to assure the scenario is available.
