### ISSUE TITLE
unknown command "config" for "odo"

### ISSUE THREAD

**Issue by kenuenoibm** [openshift-labs/learn-katacoda#477]
Hello,

I am working on "Developing with odo" scenario and having the following error message in "Step 3 of 7".

$ odo config view
Error: unknown command "config" for "odo"
Run 'odo --help' for usage.
unknown command "config" for "odo"
$

Could you please help me on this error?

**Comment by danielhelfand** [comment]
The issue is that your environment loaded using an older version of `odo` rather than `odo v1.0.0-beta2`.
 
You can run this to update to the latest version, but the command still may not work because the version of `odo` you have in your environment does not use the `config.yaml` file referenced:

 `sudo curl -L https://github.com/redhat-developer/odo/releases/download/v1.0.0-beta2/odo-linux-amd64 -o /usr/local/bin/odo && sudo chmod +x /usr/local/bin/odo`

**Comment by kenuenoibm** [comment]
@danielhelfand
That helped.
$ odo config view
COMPONENT SETTINGS
------------------------------------------------
PARAMETER         CURRENT_VALUE
Type              java
Application       app
Project           myproject
SourceType        binary
Ref
SourceLocation    target/wildwest-1.0.jar
Ports
Name              backend
MinMemory
MaxMemory
Ignore
MinCPU
MaxCPU
$

**Comment by danielhelfand** [comment]
@kenuenoibm My thought would be the rest of the tutorial should behave as expected. Again, sorry for the trouble due to the new release. Let me know if you run into any other problems.

**Comment by kenuenoibm** [comment]
@danielhelfand
after i updated it, i don't see any other issues. i just completed the scenario. thank you very much for your help.

**Comment by danielhelfand** [comment]
@kenuenoibm Thanks for working through it and helping us out. I pushed up a change that should help load the environment correctly for the tutorial.
