### ISSUE TITLE
http://learn.openshift.com Unable to load Katacoda Error

### ISSUE THREAD

**Issue by suleymandiker** [openshift-labs/learn-katacoda#523]
I took a error in http://learn.openshift.com:

"Unable to load Katacoda. Katacoda might be currently unavailable or blocked due to browser configuration"

Can you help me this subject?

Thanks.

**Comment by BenHall** [comment]
Hi @suleymandiker 

Sorry about the error. Could you please check your the browser console log and let us know if there are any errors?

**Comment by stephan-volz** [comment]
Hi @BenHall ,

I think I see the same (Chrome and Firefox on RHEL) and this is what is logged in the console:

A parser-blocking, cross site (i.e. different eTLD+1) script, http://assets.adobedtm.com/2b327a0a54b320bf1bcdb5fa39a2b896027067d9/mbox-contents-dc4a102c462e55a78aec3590996bae13ca839e07.js, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.

Access to XMLHttpRequest at 'http://katacoda.com/profile/token/id?protocol=http:&host=learn.openshift.com' from origin 'http://learn.openshift.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by ryanj** [comment]
Possibly related: The framing site may need to use (and/or enforce) a matching protocol (https) to avoid CORS / single-origin policy issues #482

**Comment by stephan-volz** [comment]
Works for me now (tested with Chrome on Linux), see also update in #526. Thanks.
