### ISSUE TITLE
clicking on "latest release" seems to end the Dashboard

### ISSUE THREAD

**Issue by austincunningham** [openshift-labs/learn-katacoda#68]
In https://learn.openshift.com/introduction/cluster-access/

When you click on the "latest release"  for the CLI the screen turns white and have no option to return to openshift dashboard 
![image](https://user-images.githubusercontent.com/16667688/32217602-667d8ede-be20-11e7-8313-a759bfd2a7ed.png)

Browser:
Chrome 61.0.3163.100 (Official Build) (64-bit)
Firefox 54(64-bit)

**Comment by GrahamDumpleton** [comment]
On most browsers I think you should be able to go right click and select back.

It seems katacoda in this case has troubles with the off site link from the framed version of the dashboard.

In that scenario, those instructions were more information than expectation that you would click on it. For the katacoda environment the ``oc`` tool is already installed. So likely never checked it worked. :-)

**Comment by austincunningham** [comment]
right click and back works :)

**Comment by BenHall** [comment]
Thanks for the feedback. We'll look at ways to make this clearer/easier.

**Comment by BenHall** [comment]
Because the link opens an internal link in the same browser tab, Github is blocking us from rendering the iframe. This is why you get a strange blank experience. I'm not sure if we can detect/capture these errors.

`Refused to display 'https://github.com/openshift/origin/releases/tag/v3.6.1' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".`

**Comment by mhausenblas** [comment]
Seems stale, please re-open if it persists.
