### ISSUE TITLE
Error on "operator-sdk generate k8s"

### ISSUE THREAD

**Issue by vaporpin** [openshift-labs/learn-katacoda#707]
I got this error for "operator sdk with go" for the step operator-sdk generate k8s. And i also realise i do not have a "vendor" folder created after this command "operator-sdk new podset-operator --type=go --skip-git-init". Maybe that's why the error?

$ operator-sdk generate k8s
Error: chdir /root/tutorial/go/src/github.com/redhat/podset-operator/vendor/k8s.io/code-generator: no such file or directory
Usage:
  operator-sdk generate k8s [flags]

Flags:
  -h, --help   help for k8s

**Comment by madorn** [comment]
@vaporpin  i was able to replicate the issue. investigating.

**Comment by mhrivnak** [comment]
I'm seeing that `k8s.io/gengo` requires `k8s.io/klog`, and it's failing to satisfy the latter dependency when running `operator-sdk new`. It might require pinning some prior release of gengo or similar. I'll keep digging.

**Comment by mhrivnak** [comment]
I was able to get `dep ensure` to complete successfully. I added this to `Gopkg.toml`:

```
[[override]]
  name = "k8s.io/gengo"
  revision = "e0e292d8aa122d458174e1bef5f142b4d0a67a05"
```

I found [this commit](https://github.com/kubernetes/gengo/commit/565683fea29eeb99987bd45fd485f148eda97471) in gengo from 6 days ago with subject "Switch to klog v2", so I just tried its parent commit, and dep ensure works again.

That said, I'm not sure what the right way will be to fix this. Presumably it'll require a change in operator-sdk.

**Comment by mhrivnak** [comment]
Next problem came when I tried to compile and run in step 6. May need to pin an older version of klog.

```
vendor/k8s.io/client-go/transport/round_trippers.go:70:11: cannot convert klog.V(9) (type klog.Verbose) to type bool
vendor/k8s.io/client-go/transport/round_trippers.go:72:11: cannot convert klog.V(8) (type klog.Verbose) to type bool
vendor/k8s.io/client-go/transport/round_trippers.go:74:11: cannot convert klog.V(7) (type klog.Verbose) to type bool
vendor/k8s.io/client-go/transport/round_trippers.go:76:11: cannot convert klog.V(6) (type klog.Verbose) to type bool
Error: failed to build operator to run locally: (failed to exec []string{"go", "build", "-o", "build/_output/bin/podset-operator-local","cmd/manager/main.go"}: exit status 2)
```

**Comment by mhrivnak** [comment]
I pinned klog to v1.0.0, which is the last release before v2.0.0, and then the rest of the exercise worked fine.

```
[[override]]
  name = "k8s.io/klog"
  version = "=v1.0.0"
```

**Comment by mhrivnak** [comment]
Our best bet may be to fork operator-sdk and maintain a patched branch for use by these exercises for as long as we keep running in this old environment. Unless operator-sdk wants to make a new release for those people who are still using OCP 3.11.

Since the exercises currently run on k8s 1.11, that limits how new of an operator-sdk release we can use. From a library standpoint, we could possibly go as far as operator-sdk 0.10.1, which is the last release to use k8s libraries from 1.13. That's within two Y-releases of the 1.11 the exercises run on, so in theory it should work from that perspective.

Also, operator-sdk 0.9.0 switched from dep to go modules, which is not supported by the go 1.10 release we have in our image currently.

Rather than make a big upgrade of multiple things, I'm inclined to just make a targeted fix on top of the operator-sdk release we're already using.

Thoughts?

**Comment by madorn** [comment]
@mhrivnak thanks for investigating!

#691 includes an upgraded podset-operator that uses go 1.13.1 and operator-sdk 0.15.2 w/ go modules on an OpenShift 4.2 environment.

It has also been updated to reflect new operator-sdk commands and a few minor changes to the podset controller logic to support updated client interface.

If you'd like to review before we merge, feel free!

Also working on updating Ansible modules to 4.2 tomorrow - may add this PR. Open to any suggestions.

**Comment by madorn** [comment]
@vaporpin @mhrivnak This exercise has been updated athttps://learn.openshift.com/operatorframework/go-operator-podset/

This issue can be closed. @BenHall
