### ISSUE TITLE
lab setup at https://learn.openshift.com/subsystems/container-internals-lab-2-0-part-5 fails, rh-ruby* packages do not exist 

### ISSUE THREAD

**Issue by peter-hansteen-at-ibm** [openshift-labs/learn-katacoda#720]
As per subject running through the lab at https://learn.openshift.com/subsystems/container-internals-lab-2-0-part-5, the lab setup fails to install fully, apparently due to missing rh-ruby* packages on the chosen mirror. This causes subsequent operations specified in the lab to fail too.

I *really* wish I had figured out a way to cut and paste text from the lab environment, I'll try attaching a screenshot that shows the last messages up to and including the failure.

![Screenshot from 2020-04-20 16-08-30](https://user-images.githubusercontent.com/64023114/79762734-6b914d00-8323-11ea-8a51-4a24d98b13ff.png)

**Comment by btannous** [comment]
@fatherlinux mind checking this out?

**Comment by btannous** [comment]
@fatherlinux checking?

**Comment by btannous** [comment]
I reached out, and Scott mentioned he will check this out in the coming week.

**Comment by troppens** [comment]
Hi @btannous, I came across the same issue and noticed some duplicate issue reports here. I am adding this post here to raise awareness, because this lab exercise seems to cover an important foundation of OpenShift. Best, Ulf.

**Comment by fatherlinux** [comment]
@troppens @btannous I wanted to let you both know that I figured out what was going on here. I've actually removed the step where I force you to build the whole supply chain in Lab 5 again. Instead, I pushed the pre-build httpd-php as well as wordpress:csc images to quay.io and just pull them back. It's way more efficient than building them again. Also, I fixed the ruby failure so that the whole supply chain will build again :-)
