### ISSUE TITLE
Downloading Istio script never finishes

### ISSUE THREAD

**Issue by tdaleibm** [openshift-labs/learn-katacoda#760]
In https://learn.openshift.com/servicemesh/1-introduction the first command automatically ran after starting the lesson never finishes. Can't do interactive lesson because of this.
![Screenshot from 2020-05-08 11-37-59](https://user-images.githubusercontent.com/55508325/81422043-71a76c00-9120-11ea-9e36-78249f8adfa1.png)

**Comment by btannous** [comment]
Thanks for the report.  Important to note that this tutorial is based on 1.0.5 istio on OCP 3.11.  Not OpenShift 4.x using OpenShift Service Mesh <which is based on istio>.  

I’m looking at redoing these to account for that change and update this, tied up in a few things right now though.

Regardless, this looks similar to https://github.com/openshift-labs/learn-katacoda/issues/750

The run-init.sh script doesn’t seem to run which the script that you are seeing relies on.  You could CTRL-C out of that, or click the + and open a new terminal window and manually run the script.  See here: https://github.com/openshift-labs/learn-katacoda/blob/master/servicemesh/1-introduction/run-init.sh

`wget -c https://github.com/istio/istio/releases/download/1.0.5/istio-1.0.5-linux.tar.gz -P /root/installation`
is pretty much what you need. <but note upstream istio is currently on 1.5, so expect changes>

Should be able to at least fix the scripts here at some point soon.

**Comment by btannous** [comment]
+ @yanaga @jamesfalkner I see you worked on these istio tutorials a while ago, maybe you can do a quick fix and let me know if you still use them for things (or know who does)?

I’d like to revamp them completely with an OpenShift Service Mesh oriented content (on 4.x and using the svc mesh operator instead) + depreciate these and remove these since they are broken.

**Comment by jamesfalkner** [comment]
@BenHall it appears that the underlying scripts for this scenario in `run-init.sh` don't run in the background properly. If I run the commands manually by opening another terminal I'm able to complete the scenario.

There are 7 more istio scenarios that rely on this background behavior so if you could fix it for this one my guess is it fixes it for all.

**Comment by btannous** [comment]
We could move the things in the run-init.sh to the set-env.sh and that should clear this up, although it moves things that used to work in the background to the foreground.  It also might not solve all the issues with all of these scenarios.

I have a few issues with fixing them though.

1) These istio labs are old.  So should I spend time to debug them all?
Not to mention I'm not sure who uses them.  I've asked a few different people and not sure yet.
2) OpenShift Service Mesh is out and should replace them.  I want to do this, but haven't started yet, and want to make sure I hit anything that (1) is using / needing to replace them.

Maybe the answer is, refresh the same modules to use OpenShift Service Mesh instead of the older 1.0 istio and fix any issues that come up because of that.

That being said, there is obviously demand for some service mesh scenarios <given the issues and stats>.

**Comment by nexus-Six** [comment]
It seems at the moment all of the Istio Labs are broken due to `run-init.sh` not being executed.  While it would be great to have updated OpenShift ServicMesh Labs I would suggest that a quick fix to get the current state running again would be more important.

These labs a great resource to point customers/partners to but if a whole chapter will not even start it has the adverse effect.
