### ISSUE TITLE
Linux Container Internals 2.0 - Lab 5: Container Orchestration - not working

### ISSUE THREAD

**Issue by Mita201** [openshift-labs/learn-katacoda#797]
Complete!
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: linux.darkpenguin.net
 * centos-sclo-rh: mirror1.hs-esslingen.de
 * centos-sclo-sclo: mirror1.hs-esslingen.de
 * extras: linux.darkpenguin.net
 * updates: ftp.hosteurope.de
No package rh-ruby22 available.
No package rh-ruby22-ruby-devel available.
No package rh-ruby22-rubygem-rake available.
No package v8314 available.
No package rh-ruby22-rubygem-bundler available.
No package nodejs010 available.
Error: Nothing to do
The command '/bin/sh -c yum install -y --nogpgcheck centos-release-scl &&     INSTALL_PKGS="rh-ruby22 rh-ruby22-ruby-devel rh-ruby22-rubygem-rake v8314 rh-ruby22-rubygem-bundler nodejs010" &&     yum install -y --nogpgcheck --setopt=tsflags=nodocs $INSTALL_PKGS && rpm -V $INSTALL_PKGS &&     yum clean all -y' returned a non-zero code: 1
make: *** [httpd-ruby.o] Error 1
make: Leaving directory `/root/labs/lab2-step4'
$ docker tag wordpress wordpress:csc
Error response from daemon: no such id: wordpress

**Comment by fatherlinux** [comment]
@Mita201 Thanks for reporting the bug, I've actually fixed the root cause and also made the lab more efficient by caching the image and not forcing the user to rebuild the whole supply chain in two different labs. I'd like to invite you back to check out the new version: https://learn.openshift.com/subsystems/container-internals-lab-2-0-part-5
