### ISSUE TITLE
Linux Container Internals 2.0 - Lab 5 does not work

### ISSUE THREAD

**Issue by MaroWielki** [openshift-labs/learn-katacoda#846]
Hi,
The make command fails becouse the Dockerfile in /root/labs/lab2-step4/httpd-ruby ries to install rh-ruby22 and v8314 node010 that are not available.

I changed all the ruby22 to ruby 23, node010 to rh-node10 and removed v8314 in INSTALL_PKGS and I am able to proceed

**Comment by fatherlinux** [comment]
@MaroWielki  Thanks for reporting the bug, I've actually fixed the root cause and also made the lab more efficient by caching the image and not forcing the user to rebuild the whole supply chain in two different labs. I'd like to invite you back to check out the new version: https://learn.openshift.com/subsystems/container-internals-lab-2-0-part-5
