### ISSUE TITLE
Linux Container Internals 2.0 - Lab 5: Container Orchestration - wordpress error

### ISSUE THREAD

**Issue by garypx** [openshift-labs/learn-katacoda#847]
This lab doesn't complete, 

The command '/bin/sh -c yum install -y --nogpgcheck centos-release-scl &&     INSTALL_PKGS="rh-ruby22 rh-ruby22-ruby-devel rh-ruby22-rubygem-rake v8314 rh-ruby22-rubygem-bundler nodejs010" &&     yum install -y --nogpgcheck --setopt=tsflags=nodocs $INSTALL_PKGS && rpm -V $INSTALL_PKGS &&     yum clean all -y' returned a non-zero code: 1
make: *** [httpd-ruby.o] Error 1
make: Leaving directory `/root/labs/lab2-step4'
$ docker tag wordpress wordpress:csc
Error response from daemon: no such id: wordpress

**Comment by fatherlinux** [comment]
@garypx Thanks for reporting the bug, I've actually fixed the root cause and also made the lab more efficient by caching the image and not forcing the user to rebuild the whole supply chain in two different labs. I'd like to invite you back to check out the new version: https://learn.openshift.com/subsystems/container-internals-lab-2-0-part-5
